package com.shalatan.devjoke.di

import android.content.Context
import androidx.room.Room
import com.shalatan.devjoke.database.JokeDAO
import com.shalatan.devjoke.database.JokeDatabase
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton

@InstallIn(SingletonComponent::class)
@Module
object DatabaseModule {

    @Provides
    fun provideMovieDao(appDatabase: JokeDatabase): JokeDAO {
        return appDatabase.jokesDao()
    }

    /**
     * Our project doesn't own the AppDatabase class either, because it is generated by Room.
     * We can't constructor inject AppDatabase, but we can use an @Provides function to provide it, too.
     */
    @Provides
    @Singleton
    fun provideDatabase(@ApplicationContext appContext: Context): JokeDatabase {
        return Room.databaseBuilder(
            appContext,
            JokeDatabase::class.java,
            "jokes.db"
        ).build()
    }
}